name: Generate Snake

on:
  schedule:
    # каждые 12 часов
    - cron: "0 */12 * * *"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: akoffice933-maker
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: Platane/snk/actions/publish@v3
        with:
          github_user_name: akoffice933-maker
          publish_dir: ./dist
          publish_branch: output
